### ISSUE TITLE
Required numpy version (1.26.4)

### ISSUE THREAD

**Issue by jmoyden** [juba/pyobsplot#38]
When installing with conda (using conda-forge channel) pyobsplot causes a downgrade to the current numpy installation as it requires version 1.26.4

Is this requirement necessary as this is now a major version number downgrade from the current stable numpy version?

**Comment by juba** [comment]
You're right, in fact `pyobsplot` doesn't directly depends on `numpy` 1.26.4, but we depend on `pyarrow` 15.0.0 which doesn't allow to use  `numpy` >= 2.0.

This will be fixed with the next version as we depend on more recent pyarrow, but I would not advise to use it for now as the API will be changing a bit and is not stabilized yet.

Sorry for the inconvenience.
